apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop-devops-backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 858431073453.dkr.ecr.us-east-1.amazonaws.com/workshop-devops/prod/backend:v1
        ports:
        - containerPort: 80
